# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [KABIRI Salim](https://github.com/KsalimK)
- [Ait Lemqeddem Amine](https://github.com/AmineAitLemqeddem)

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from sdia_python.lab2.utils import get_random_number_generator

0.6383630634967252


In [4]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)


<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [21]:
int_vector1=np.ones(100)
int_vector2=np.array([1 for i in range(100)])


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Create a vector with values ranging from 10 to 49

In [27]:
rand_vect=np.random.randint(10,50,2)
rand_vect

array([19, 25])

Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [36]:
vect_construction1=np.linspace(0,0.8,5)
vect_construction1

vect_construction2=np.arange(0,1,0.2) #stop+1 to achieve the stop desired
vect_construction2

array([0. , 0.2, 0.4, 0.6, 0.8])

Convert a float array into an integer array in place

In [40]:
float_array=np.array([1,23,np.pi,np.sqrt(5)])
int_array=float_array.astype(int)

int_array


array([ 1, 23,  3,  2])

Given a boolean array

- return the indices where 
- negate the array inplace? 

In [62]:
bool_array=np.array([False,False,True,False,True]) #rand_vect=np.random.randint(0,2,nb point)  , rand_vect.astype(bool)
Indices_True=np.nonzero(bool_array==True)
Indices_True
Indices_False=np.nonzero(bool_array==False)

##########Negate the array##########
bool_array_negation=(bool_array==False) ## np.invert
bool_array_negation


array([ True,  True, False,  True, False])

Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [106]:
u=np.array([1,2,3,4,5])
v=np.array([6,7,8,9,0])
################inner product##########################
inner_product1=np.vdot(u,v)
inner_product1


inner_product2=np.dot(u,v.T)
inner_product2

###############outer product####################
outer_product1=np.outer(u,v)
outer_product1

v_reshape=v.reshape((1,5))
u_reshape=u.reshape((5,1))
outer_product2=np.dot(u_reshape,v_reshape)

outer_product2

#############the outer sum##########

###Method1#####
M1=np.zeros((len(u),len(v)))
for i in range(len(u)):
    for j in range(len(v)):
        M1[i][j]=u[i]+v[j]
M1

####Method2####

M2=np.array([u]*len(u)).T+v

M2

M1==M2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [273]:
########  M Méthode list of list #######

M=[[0,1,2],[3,4,5],[6,7,7]]
M[1][1]

########  M Méthode 1 numpy array #######
M1=np.array([[0,1,2],[3,4,5],[6,7,8]])
M1
M1[1][1]

########  M Méthode 2 numpy array #######
M2=np.arange(0,9,1)
M2=M2.reshape((3,3))
M2
M2[1][1]

############################################################################
#Par la suite nous allons utiliser M2 comme variable de stockage de la matrice M#
############################################################################

########### Inverser la première et la deuxième ligne########
M2_copy=np.copy(M2)
M2_copy[0,:],M2_copy[1,:]=M2[1,:],M2[0,:]
M2_copy

########## Extraction de la sous-matrice #############

##### Méthode 1 ######
submatrix1=M2[1:,1:]
submatrix1
##### Méthode 2 ######
submatrix2=M2[1:3,1:3]
submatrix2
##### Méthode 3 ######
submatrix3=M2[1:][:,1:]
submatrix3

######## diagonale de M #####
##### Méthode 1 ######
diag1=np.diag(M2)
diag1
##### Méthode 2 ######
diag2=np.array([M2[i][i] for i in range(len(M))])
diag2
##### Méthode 3 ######
diag3=M2[1:][:,1:]
diag3

######################## M^3 ##########################

##### Méthode 1 ######
M3_1=np.dot(np.dot(M2,M2),M2)

##### Méthode 2 ######
D,V =np.linalg.eig(M2)
matrixD=np.zeros((3,3))
matrixD[0][0]=D[0]
matrixD[1][1]=D[1]
matrixD[2][2]=D[2]
M3_2=np.dot(np.dot(np.linalg.inv(V),matrixD**3),V)
#########
 #Mathématiquement, cette méthode devrait donner le bon résultat mais j'obtiens un résultat différent (à voir avec le prof)
########   

################## v.T M and MN############
v=np.array([1,2,3])
N=np.array([[1,2,3],[4,5,6],[7,8,9]])


vTM=np.dot(v.T,N)
vTM

MN=np.dot(M,N)
MN


##################### vectorize the matrix m #################
M3_copy=np.copy(M2)
vect1=M3_copy.reshape(9)
vect1


vect2=M3_copy.T.reshape(9)
vect2

##################### row-wise and column-wise multiplication########
v=np.array([1,2,3])

Mv_row_wise=M2*v.reshape((3,1))
Mv_row_wise

Mv_column_wise=M2*v
Mv_column_wise




array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [295]:
def is_symmetric(x):
    """function that checks whether a given n x n matrix is symmetric

    Args:
        x (array): the matrix to test

    Returns:
        bool: True if x is symmetric , False if not
    """
    
        
    return np.array_equal(x,x.T)

x1=np.array([[1,2,3],[4,5,6],[6,7,8]])
is_symmetric(x1) #False

x2=np.array([[1,2,3],[2,2,3],[3,3,3]])
is_symmetric(x2) #True


True

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

In [315]:
rng=get_random_number_generator(0)

simulation1= rng.binomial(1,0.4,1000)
mean1=np.mean(simulation1)
var1=np.var(simulation1)
simulation1 , mean1 , var1


simulation2= np.array([rng.binomial(1,0.4) for i in range(1000)])
mean2=np.mean(simulation2)
var2=np.var(simulation2)
simulation2 , mean2 , var2


(array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column

In [336]:
Gaussian_matrix=rng.normal(0,1,(50,100))
Gaussian_matrix

Gaussian_matrix_abs=np.abs(Gaussian_matrix)

Sum_row = Gaussian_matrix.sum(axis=1)
Sum_row

Sum_column = Gaussian_matrix.sum(axis=0)
Sum_column

norm_row = np.linalg.norm(Gaussian_matrix,axis=1)
norm_row

norm_row = np.linalg.norm(Gaussian_matrix,axis=0)
norm_row

array([6.90713452, 7.59743836, 6.39794324, 6.30824988, 6.72247908,
       7.83086859, 7.17884951, 6.31719148, 7.31782602, 6.50877941,
       7.64778918, 6.75465775, 7.70383317, 7.95805585, 7.80358484,
       6.38619948, 6.91134172, 7.01787848, 7.6421603 , 7.121144  ,
       7.37147808, 7.23229065, 5.79204245, 6.55315666, 8.29672682,
       6.39835342, 6.92682858, 6.10666278, 5.48991026, 8.05534669,
       6.98039514, 6.15363546, 7.00213912, 7.49464636, 7.04862755,
       8.25882555, 5.78575974, 7.17239548, 6.51651865, 7.4518577 ,
       6.63259437, 7.70547305, 6.19774303, 6.68049204, 5.87382348,
       7.48493831, 7.42902109, 7.32959815, 6.85346254, 7.14799798,
       6.05141195, 8.16177717, 7.71700655, 7.30239983, 6.90319175,
       6.50284532, 7.87056734, 6.79009034, 6.41525845, 7.21111722,
       6.46138786, 8.28157768, 7.57503503, 6.08340822, 7.1520737 ,
       7.12325514, 7.94959215, 6.59253751, 7.22887438, 8.21942592,
       6.55157429, 6.95251663, 6.72752296, 6.23067742, 6.12147